(function(){videojs.Vimeo=videojs.MediaTechController.extend({init:function(a,d,e){videojs.MediaTechController.call(this,a,d,e);if("undefined"!=typeof d.source)for(var g in d.source)a.options()[g]=d.source[g];this.player_=a;this.player_el_=document.getElementById(this.player_.id());this.player_.controls(!1);this.id_=this.player_.id()+"_vimeo_api";this.el_=videojs.Component.prototype.createEl("iframe",{id:this.id_,className:"vjs-tech",scrolling:"no",marginWidth:0,marginHeight:0,frameBorder:0});this.el_.setAttribute("webkitAllowFullScreen",
"");this.el_.setAttribute("mozallowfullscreen","");this.el_.setAttribute("allowFullScreen","");this.player_el_.insertBefore(this.el_,this.player_el_.firstChild);this.baseUrl=("file:"===document.location.protocol?"http:":document.location.protocol)+"//player.vimeo.com/video/";this.vimeo={};this.vimeoInfo={};var f=this;this.el_.attachEvent?this.el_.attachEvent("onload",vjs.bind(f,f.onLoad)):this.el_.onload=function(){f.onLoad()};this.startMuted=a.options().muted;this.src(a.options().src)}});videojs.Vimeo.prototype.dispose=
function(){this.vimeo&&(this.vimeo.removeEvent("ready"),this.vimeo.api("unload"),delete this.vimeo);this.el_&&this.el_.parentNode.removeChild(this.el_);videojs.MediaTechController.prototype.dispose.call(this)};videojs.Vimeo.prototype.src=function(a){if(a){this.isReady_=!1;var d;if(/player\.vimeo.com/.test(a)){if(d=/video\/([A-z0-9]+)/,a=a.match(d))this.videoId=a[1]}else if(d=/^.*(vimeo\.com\/)((channels\/[A-z]+\/)|(groups\/[A-z]+\/videos\/))?([0-9]+)/,a=a.match(d))this.videoId=a[5];a={api:1,byline:0,
portrait:0,show_title:0,show_byline:0,show_portait:0,fullscreen:1,player_id:this.id_,autoplay:this.player_.options().autoplay?1:0,loop:this.player_.options().loop?1:0,color:this.player_.options().color||""};"#"===a.color.substring(0,1)&&(a.color=a.color.substring(1));this.el_.src=this.baseUrl+this.videoId+"?"+videojs.Vimeo.makeQueryString(a)}};videojs.Vimeo.prototype.load=function(){};videojs.Vimeo.prototype.ended=function(){this.vimeo.api("play")};videojs.Vimeo.prototype.play=function(){this.vimeo.api("play")};
videojs.Vimeo.prototype.pause=function(){this.vimeo.api("pause")};videojs.Vimeo.prototype.paused=function(){return 1!==this.vimeoInfo.state&&3!==this.vimeoInfo.state};videojs.Vimeo.prototype.currentTime=function(){return this.vimeoInfo.time||0};videojs.Vimeo.prototype.setCurrentTime=function(a){this.vimeo.api("seekTo",a);this.player_.trigger("timeupdate")};videojs.Vimeo.prototype.duration=function(){return this.vimeoInfo.duration||0};videojs.Vimeo.prototype.buffered=function(){return videojs.createTimeRange(0,
this.vimeoInfo.buffered*this.vimeoInfo.duration||0)};videojs.Vimeo.prototype.volume=function(){return this.vimeoInfo.muted?this.vimeoInfo.muteVolume:this.vimeoInfo.volume};videojs.Vimeo.prototype.setVolume=function(a){this.vimeo.api("setvolume",a);this.vimeoInfo.volume=a;this.player_.trigger("volumechange")};videojs.Vimeo.prototype.currentSrc=function(){return this.el_.src};videojs.Vimeo.prototype.muted=function(){return this.vimeoInfo.muted||!1};videojs.Vimeo.prototype.setMuted=function(a){a?(this.vimeoInfo.muteVolume=
this.vimeoInfo.volume,this.setVolume(0)):this.setVolume(this.vimeoInfo.muteVolume);this.vimeoInfo.muted=a;this.player_.trigger("volumechange")};videojs.Vimeo.prototype.onReady=function(){this.isReady_=!0;this.triggerReady();this.player_.trigger("loadedmetadata");this.startMuted&&(this.setMuted(!0),this.startMuted=!1)};videojs.Vimeo.prototype.onLoad=function(){this.vimeo&&this.vimeo.api&&(this.vimeo.api("unload"),delete this.vimeo);this.vimeo=$f(this.el_);this.vimeoInfo={state:-1,volume:1,muted:!1,
muteVolume:1,time:0,duration:0,buffered:0,url:this.baseUrl+this.videoId,error:null};var a=this;this.vimeo.addEvent("ready",function(d){a.onReady();a.vimeo.addEvent("loadProgress",function(e,d){a.onLoadProgress(e)});a.vimeo.addEvent("playProgress",function(d,g){a.onPlayProgress(d)});a.vimeo.addEvent("play",function(d){a.onPlay()});a.vimeo.addEvent("pause",function(d){a.onPause()});a.vimeo.addEvent("finish",function(d){a.onFinish()});a.vimeo.addEvent("seek",function(d,g){a.onSeek(d)})})};videojs.Vimeo.prototype.onLoadProgress=
function(a){var d=!this.vimeoInfo.duration;this.vimeoInfo.duration=a.duration;this.vimeoInfo.buffered=a.percent;this.player_.trigger("progress");d&&this.player_.trigger("durationchange")};videojs.Vimeo.prototype.onPlayProgress=function(a){this.vimeoInfo.time=a.seconds;this.player_.trigger("timeupdate")};videojs.Vimeo.prototype.onPlay=function(){this.vimeoInfo.state=1;this.player_.trigger("play")};videojs.Vimeo.prototype.onPause=function(){this.vimeoInfo.state=2;this.player_.trigger("pause")};videojs.Vimeo.prototype.onFinish=
function(){this.vimeoInfo.state=0;this.player_.trigger("ended")};videojs.Vimeo.prototype.onSeek=function(a){this.player_.trigger("seeking");this.vimeoInfo.time=a.seconds;this.player_.trigger("timeupdate");this.player_.trigger("seeked")};videojs.Vimeo.prototype.onError=function(a){this.player_.error=a;this.player_.trigger("error")};videojs.Vimeo.isSupported=function(){if(!(10<=videojs.Flash.version()[0])){if(-1!=navigator.userAgent.indexOf("Opera"))return!1;var a=-1!=navigator.userAgent.indexOf("Mac OS X"),
d=-1<navigator.userAgent.toLowerCase().indexOf("firefox");if(a&&d)return!1;a=/Trident\/([\d\.]+)/;if(a.test(navigator.userAgent)){var e;null!=a.exec(navigator.userAgent)&&(e=parseFloat(RegExp.$1));if(e&&7>e)return!1}}return!0};videojs.Vimeo.prototype.supportsFullScreen=function(){return!1};videojs.Vimeo.canPlaySource=function(a){return"video/vimeo"==a.type};videojs.Vimeo.makeQueryString=function(a){var d=[],e;for(e in a)a.hasOwnProperty(e)&&d.push(encodeURIComponent(e)+"="+encodeURIComponent(a[e]));
return d.join("&")};(function(){function a(m){return new a.fn.init(m)}function d(a,c,b){if(!b.contentWindow.postMessage)return!1;a=JSON.stringify({method:a,value:c});b.contentWindow.postMessage(a,h)}function e(a){var c,b;try{c=JSON.parse(a.data),b=c.event||c.method}catch(d){}"ready"!=b||l||(l=!0);if(!/^https?:\/\/player.vimeo.com/.test(a.origin))return!1;"*"===h&&(h=a.origin);a=c.value;var e=c.data,k=""===k?null:c.player_id;c=k&&f[k]?f[k][b]:f[b]?f[b]:void 0;b=[];if(!c)return!1;void 0!==a&&b.push(a);
e&&b.push(e);k&&b.push(k);return 0<b.length?c.apply(null,b):c.call()}function g(a,c,b){b?(f[b]||(f[b]={}),f[b][a]=c):f[a]=c}var f={},l=!1,h="*";a.fn=a.prototype={element:null,init:function(a){"string"===typeof a&&(a=document.getElementById(a));this.element=a;return this},api:function(a,c){if(!this.element||!a)return!1;var b=this.element,e=""!==b.id?b.id:null,f=c&&c.constructor&&c.call&&c.apply?null:c,h=c&&c.constructor&&c.call&&c.apply?c:null;h&&g(a,h,e);d(a,f,b);return this},addEvent:function(a,
c){if(!this.element)return!1;var b=this.element,e=""!==b.id?b.id:null;g(a,c,e);"ready"!=a?d("addEventListener",a,b):"ready"==a&&l&&c.call(null,e);return this},removeEvent:function(a){if(!this.element)return!1;var c=this.element,b=""!==c.id?c.id:null;a:{if(b&&f[b]){if(!f[b][a]){b=!1;break a}f[b][a]=null}else{if(!f[a]){b=!1;break a}f[a]=null}b=!0}"ready"!=a&&b&&d("removeEventListener",a,c)}};a.fn.init.prototype=a.fn;window.addEventListener?window.addEventListener("message",e,!1):window.attachEvent("onmessage",
e);return window.Froogaloop=window.$f=a})()})();
